name: deploy

on: 
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '14' ]

    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.0
        with:
          username: ${{ secrets.USERNAME }}
          reponame: https://github.com/ifanfairuz/ifanfairuz.github.io.git
          token: ${{ secrets.GITHUB_TOKEN }}
